version: '3.8'

services:
  
  # Golang API
  api:
    build:
      context: ./api
      dockerfile: amd64
      
    restart: always

    environment:
      - API_APP_CONFIG=${API_CONFIG}
      - API_DB_TYPE=postgres
      - API_DB_HOST=db
      - API_DB_PORT=5432
      - API_DB_USERNAME=${DB_USERNAME}
      - API_DB_PASSWORD=${DB_PASSWORD}
      - API_DB_NAME=${DB_DBNAME}

    networks: 
      - api-db

    depends_on:
      - db

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Postgres DB
  db:
    image: postgres:alpine
    restart: always
    
    networks:
      - api-db

    environment: 
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DBNAME} 

    # Comment out ports here if you do not want outside DB access
    ports:
      - ${DB_OUT_PORT}:5432

    # Uncomment the following lines if you want to persist data
    #volumes:
    #  - ./db/data:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  api-db:
    driver: bridge
