name: API build test (ARM)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner:
          - arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build and run Docker Compose services and check API health status
        run: |
          chmod +x test-amd64.sh
          ./test-amd64.sh