name: API build test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.7

      - name: Build and run API Docker-Compose
        run: ./run-amd64.sh

      - name: Wait for API to start
        run: sleep 5

      - name: Test API endpoint
        run: curl http://localhost:8080/mock-api/v1/mock/healthz

      - name: Stop API container
        run: docker-compose -f docker-compose-amd64.yml down