name: Raw API Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.7'

    - name: Test config module
      run: cd ./api/config &&
           go mod init github.com/Timotej979/Celtra-challenge/api/config &&
           go get github.com/spf13/cobra &&
           go get github.com/spf13/viper &&
           go get github.com/spf13/pflag &&
           go test

    - name: Test DAL module
      run: cd ./api/dal &&
           go mod init github.com/Timotej979/Celtra-challenge/api/dal &&
           go test

      
